ARG LOGSTASH_VERSION=7.11.0
FROM docker.elastic.co/logstash/logstash:$LOGSTASH_VERSION

COPY ./logstash-output-newrelic-*.gem /logstash/install/logstash-output-newrelic.gem

RUN logstash-plugin install --no-verify --local /logstash/install/logstash-output-newrelic.gem